package name.ihorko.problems.problem_002__Even_Fibonacci_numbers;

import java.util.ArrayList;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 *
 * Answer: 4613732
 */

public class Problem_002 {
    public static void main(String[] args) {
        int max = 4_000_000;
        ArrayList<Integer> fibonacci = new ArrayList<>();
        fibonacci.add(1);
        fibonacci.add(2);
        int i = 2;
        int sum;
        while (true) {
            sum = fibonacci.get(i-2) + fibonacci.get(i-1);
            if (sum >= max) break;
            fibonacci.add(sum);
            i++;
        }
        sum = 0;
        for (int f : fibonacci) {
            if (f%2==0) sum+=f;
        }
        System.out.println(sum);
    }
}
